### PR TITLE
my changes but improved

### PR DESCRIPTION
**Pull request by kachnov**
All of my changes that failed to merge, but slightly more concise. 

This time I added a dynamic way of loading helper functions into literally any object. For example, to pick a random value from an array, you can now use `this.helpers.arrays.pick(array)` just about anywhere. It's a bit verbose, but that's the only problem I encountered. `require_nodestation()` should replace `require()` everywhere now, except for the instances of `require()` that I've left in the code.

This is an attempt to replicate the sort of "globalness" that is achieved in BYOND. Superglobals, I guess. If there's a way to make it better or less verbose, I can do that. I'm a shitcoder so give me all of your input.

### CODE REVIEW

**Comment by kachnov** [comment]
Changed the structure of the `pick` helper to be less horrible. @hansonry can you look at this PR?

**Comment by hansonry** [comment]
Why do you attach the helpers to all the objects instead of just the objects that need it? I have a concern that the helpers thing will be a dumping ground for all functions that don't really have a home instead of making one for them. Can we change the helpers js file into some sort of names js file that will have name related functions? Thoughts?

**Comment by kachnov** [comment]
My mistake. It should only be attached to those starting with `./src/`. 

By name related functions, do you mean something like deleting the `helpers` object and replacing it with `arrays`, `strings`, etc objects? Or do you want actual functions that aren't attached to objects? (I don't know how to do this second one and still retain the same superglobal scope)

**Comment by hansonry** [comment]
Sorry for the delay some bad stuff is happening right now in my life. 

I am suggesting that you export a function called something like "createRandomName" and that would use your name table to generate a random name. You can keep the name table in the module as a local variable. Exported functions can access local module variables, but they cannot be accessed from outside the module. I do like the random function, but I would like to only apply that to arrays that need to be random instead of modifying all objects as you require them into the main program. My personal thought is that random array picking is probably going to be rare enough to warrant different implementations of it where it is needed. But if you feel like it will be used often then I would recommend making an ArrayUtilities module (.js) file that contains a function that takes an array and returns a random element. 

Thoughts?

P.S. Thanks for working with me.

Edit: I just realized I should provide an example
```
var name = ["bob", "frank"];
module.exports = {
   createRandomName: function() {
       return name[Math.floor(Math.random() * name.length)]
   }
};
```

Then inside the server.js

```
var names = require('./src/names.js');
pawn.name = names.createRandomName();
```

Did that make sense?

**Comment by kachnov** [comment]
It seems like your model will require a lot of extra code in `lists.js` and elsewhere. I may be misunderstanding, but do you want a require statement every time a helper function needs to be accessed? Such as:

`var arrayhelpers = require(./src/arrayhelpers.js');`
`var value = arrayhelpers.pick(myarray);`

That would be uglier IMO, a lot less efficient, and unlike my design, would result in the creation of multiple objects. 

Another idea I have is removing `helpers` by simply changing the definition of `require_nodestation()`. Instead of `this.helpers.arrays`, `this.helpers.strings`, etc, you could simply do `this.arrays`, `this.strings`, etc. Naturally, `this.arrays` would just be an alias for `this.helpers.arrays`.

What do you think @hansonry ? And sorry for the late response again.

**Comment by hansonry** [comment]
What extra code? Are you talking about the pick function? Because right now pick is only used for picking random names and is not needed in other locations. And as I said above I don't see pick as being used so much that we should put it everywhere (I am pretty sure that is what you are doing with require_nodestation()). I like to wait until functionality is actually duplicated in the code before writing a function for it. I am less interested in developing utility library.

As for your arrayhelpers.js, yes I think that is how I would do it. As for ugliness, I value readable code over non-ugly code. I want to keep nodestation accessible to people who are new to the project and I think in your example it is very clear what is happening. That is why for similar reasons I don't like the require_nodestation() function so much. It forces you to understand what that function is doing before you can understand what another piece of code is doing. As for performance and efficiency, I don't think we are ready to be optimizing at this level yet. Even if we were I would want to take a closer look at the many for loops in the project before we look at creating a single object, even if we do create that object over many files, it would still be pretty low on my list. Just to be clear we would only  `require(./src/arrayhelpers.js')` once in the lists.js file on the top of the file and then use it where it will be needed (I am pretty sure you already knew that).

As for your last idea. I think it cleans things up a bit, but it doesn't address any of my concerns.

Thoughts?

**Comment by kachnov** [comment]
So basically, you want to handle helpers as you would handle header files in C++?

It's not a bad idea - but my approach is more 'SS13'-ish, which is what I'm used too. If we ever reach anything close to the ridiculous amount of content that SS13 has, I think it makes more sense to automatically include files, so nobody has to spend 10 minutes scrambling around the code to see what "header files" they need when they want to write a minor feature. Are you planning to use this system for just the core files, or in content scripts as well?

One of the best things about BYOND is that you don't have to worry about complex include statements, or accidentally including the same file twice. It would feel less like I'm coding in SS13 or BYOND or a game engine, and more like I'm coding in C++ or 'real' language with this approach. While technically more correct & perhaps more efficient in terms of not polluting an object's index, it comes off to me as less consumer-friendly to BYOND or SS13 devs. 

I can see your argument, at any rate - and it doesn't seem like there's any way to perfectly replicate what BYOND does in terms of globalness while only using a JS framework and some libraries. (probably?)

The above is just my opinion on the situation, based on my personal coding style. If you would like me to do your approach, I'll be able to code it some time later. To confirm: how would I handles name lists with your approach? Something similar to `./src/arrayhelpers.js`?

**Comment by hansonry** [comment]
I feel strongly about doing this for the core files. My desire is for them to work like Node.js javascript files, however a node developer would write them (I have hardly any node experience). I care less for C/C++ style syntax. For the content scripts (Your talking like `webroot/src/types.js` right?) I am less sure about things. I have never developed that kind of file/thing/interface before. My gut says we should still to simple javascript, but it's been wrong before. And I do think it is important for the people who have created items in BYOND to feel very comfortable and at home in those files. So I would be interested in here your thoughts about it.

As for the confirmation, you have it, I will pull it, if it looks like that.

**Comment by kachnov** [comment]
@hansonry requested changes have been implemented

By the way, I have no experience in Node (well, now I do), and just some in JS. DM is my forte. So, how you choose to organize the structure of files is up to you - it will not be difficult to change later on, and with the current lack of content, it makes little difference what approach we take to file including.

**Comment by hansonry** [comment]
Hey I would like to give you credit for helping out. I am thinking a CONTRIBUTORS file. Unless you have a different idea. Is "kachnov" ok? Or would you prefer something else?

**Comment by kachnov** [comment]
Kachnov is fine

**Pull request merged**
