### PR TITLE
adds pawn names

### PR DESCRIPTION
**Pull request by kachnov**
this gives people names which show up when they say something

and adds an array helper function, pick(array)

tested

### CODE REVIEW

**Comment by hansonry** [comment]
I pulled everything but now this change isn't showing up in the master. Did I do something wrong?

**Comment by kachnov** [comment]
no idea, will test when I can

**Comment by kachnov** [comment]
sorry for the late response. It seems like the only commit that was merged right was https://github.com/hansonry/nodestation/pull/5

Can you try syncing your local code?

**Comment by hansonry** [comment]
Shoot. When you say syncing to mean pull the code down from github, or push my local code back up?
I have already pulled the changes down from github after I made them.

**Comment by kachnov** [comment]
push your local code back up. If that doesn't work and you already pulled the changes, I don't know. You'll have to replace the files manually, or I can do a PR doing so.

**Comment by hansonry** [comment]
Alright I reset hard to back before the merges. And I forced pushed those up. Hopefully this is what you were thinking of. Are you going to issue a new pull request?

**Comment by kachnov** [comment]
You force pushed the new files or the hard reset?

**Comment by hansonry** [comment]
I forced pushed the hard reset

**Comment by kachnov** [comment]
Ok. Sorry for the late response, I've been busy as of late. I'll do an updated PR when I get the time.

**Comment by hansonry** [comment]
Sounds good, I liked the path you were on.

**Pull request merged**
